#pragma once

typedef enum { TYPE_INT64, TYPE_INT32, TYPE_INT16, TYPE_INT8, TYPE_INT1, TYPE_INT, TYPE_UINT64, TYPE_UINT32, TYPE_UINT16, TYPE_UINT8, TYPE_UINT1, TYPE_UINT, TYPE_CHAR, TYPE_VAR, TYPE_BOOL, TYPE_STR, TYPE_VOID } DataType; // Data types
typedef enum { INIT, UNINIT } VarStates; // Var state
